# Generated by Django 5.2.7 on 2025-10-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_openrouterusage_agent_memory_agent_mind_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='watchers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
