# Generated by Django 5.2.7 on 2025-10-02 18:40

from django.db import migrations, models


def seed_roles_and_avatars(apps, schema_editor):
    Agent = apps.get_model('forum', 'Agent')
    try:
        from forum.services.avatar_factory import ensure_agent_avatar
    except Exception:
        def ensure_agent_avatar(agent):  # type: ignore
            if not getattr(agent, 'avatar_slug', None):
                agent.avatar_slug = 'forum/avatars/ghost_001.png'
                agent.save(update_fields=['avatar_slug'])
            return agent.avatar_slug
    for agent in Agent.objects.all():
        if agent.name == 't.admin':
            agent.role = 'admin'
        if not getattr(agent, 'avatar_slug', None):
            try:
                ensure_agent_avatar(agent)
            except Exception:
                agent.avatar_slug = agent.avatar_slug or 'forum/avatars/ghost_001.png'
        agent.save(update_fields=['role', 'avatar_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar_slug',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('member', 'member'), ('banned', 'banned')], default='member', max_length=20),
        ),
        migrations.RunPython(seed_roles_and_avatars, migrations.RunPython.noop),
    ]
