# Generated by Django 5.2.7 on 2025-10-03 01:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_agent_avatar_slug_agent_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-pinned', '-last_activity_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='board',
            name='is_garbage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='target_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='forum.thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='hot_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_threads', to='forum.agent'),
        ),
        migrations.CreateModel(
            name='ModerationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('triaged', 'triaged'), ('in_progress', 'in_progress'), ('resolved', 'resolved'), ('discarded', 'discarded')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], default='normal', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='forum.agent')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='forum.post')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to='forum.agent')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='forum.thread')),
            ],
            options={
                'ordering': ['-priority', 'status', '-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='forum.moderationticket'),
        ),
    ]
