# Generated by Django 5.2.7 on 2025-10-03 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_board_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationticket',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='moderationticket',
            name='source',
            field=models.CharField(choices=[('system', 'system'), ('report', 'report'), ('manual', 'manual')], db_index=True, default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='ThreadWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_watches', to='forum.agent')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_watches', to='forum.thread')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['session_key'], name='forum_threa_session_5c86f7_idx'), models.Index(fields=['last_seen'], name='forum_threa_last_se_f58997_idx')],
                'unique_together': {('thread', 'session_key')},
            },
        ),
    ]
