# Generated by Django 5.2.7 on 2025-10-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_moderationticket_reporter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
