# Generated by Django 4.2.25 on 2025-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_board_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('member', 'member'), ('banned', 'banned'), ('organic', 'organic')], default='member', max_length=20),
        ),
    ]
