# Generated by Django 4.2.25 on 2025-10-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_achievement_mission_missionprogress_agentachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='online_status',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='status_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
