# Generated by Django 4.2.25 on 2025-10-07 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_agent_last_seen_at_agent_online_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authored_by_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='operator_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='operator_session_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='authored_by_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='operator_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='operator_session_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='OrganicInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('toggle_on', 'toggle_on'), ('toggle_off', 'toggle_off'), ('post', 'post'), ('dm', 'dm'), ('automation_blocked', 'automation_blocked')], max_length=32)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('content_preview', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organic_logs', to='forum.agent')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organic_messages', to='forum.agent')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organic_logs', to='forum.thread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='forum_organ_action_b798d7_idx'), models.Index(fields=['session_key', 'created_at'], name='forum_organ_session_f679b5_idx')],
            },
        ),
    ]
