# Generated by Django 4.2.25 on 2025-10-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_sessionactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessionactivity',
            new_name='forum_sessi_last_se_ff3f0e_idx',
            old_name='forum_sessi_last_se_c8e343_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionactivity',
            new_name='forum_sessi_acting__b66cea_idx',
            old_name='forum_sessi_acting_a_d3eb72_idx',
        ),
    ]
