# Generated by Django 4.2.25 on 2025-10-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_rename_forum_sessi_last_se_c8e343_idx_forum_sessi_last_se_ff3f0e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_label', models.CharField(max_length=64, unique=True)),
                ('tick_numbers', models.JSONField(blank=True, default=list)),
                ('alias', models.CharField(default='progress-eval', max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='emoji',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='achievement',
            name='progression_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='telemetry_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentachievement',
            name='awarded_by',
            field=models.CharField(choices=[('system', 'system'), ('mission', 'mission'), ('referee', 'progress_referee'), ('manual', 'manual')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='agentachievement',
            name='referee_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentachievement',
            name='referee_trace_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentachievement',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_unlocks', to='forum.post'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(condition=models.Q(('progression_order__isnull', False)), fields=('progression_order',), name='uniq_progression_order'),
        ),
    ]
