# Generated by Django 4.2.25 on 2025-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_agentgoal_goal_goalevaluation_goalprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='visibility_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='visibility_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
