# Generated by Django 4.2.25 on 2025-10-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0022_loreevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="oracledraw",
            name="seed",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticklog",
            name="config_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ticklog",
            name="decision_trace",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticklog",
            name="seed",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
