# Generated by Django 4.2.25 on 2025-10-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0023_oracledraw_seed_ticklog_config_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="subject",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
